### ISSUE TITLE
Cucumber factory and factory girl transient

### ISSUE THREAD

**Issue by denzelem** [makandra/cucumber_factory#26]
Let's say you have a polymorphic model `Attachment` 

```
FactoryGirl.define do
  factory :attachment do
    transient do
      user nil 
      mail nil
    end

    record { user || mail }
end
```

Then I would like to say the following in a cucumber scenario:

```
Given there is a user
  And there is an attachment with the user above
  And there is a mail
  And there is an attachment with the mail above
```

But the transient attribute is `nil` and not `User.last` and ` Mail.last`.

Needs further research, maybe I'm using it wrong. Passing a "real" argument and not `above` seems to work like expected:

```
And there is an attachment with the mail "Hallo"
```

**Comment by kratob** [comment]
`above` only works for associations, because cucumber_factory asks the association which class to call `.last` on. One could potentially try to guess from the attribute name `user` that you probably intended to get `User.last`, but that could be a bit error prone.

Using an explicitly named record should work:
```
Given "my user" is a user
  And there is an attachment with the user "my user"
```
