### ISSUE TITLE
Cucumber factory (2.1.0+) will not always find the right object when using a transient attribute

### ISSUE THREAD

**Issue by FLeinzi** [makandra/cucumber_factory#36]
Since the last upgrade of cucumber_factory we can use transient attributes, if they are named after another class. Unfortunately this is actually not working in every case.

Given we have a class `Library` with a transient attribute `book` in its factory, and there is also a class `Book` in our project.  we have this setup in our scenario:

```text
Given there is a library (has books) with the name "Public library", book "Lord of the Rings"
  And there is a library (has books) with the name "School library", book "Lord of the Rings"
```

The second step will result in `create(:library, :has_books, name: "School library", book: library_1)`, which is not the expected expression.

**Comment by kratob** [comment]
This is not quite what I experienced. My example was along the lines of
```
Given there is a library (has books) with the name "Public library", book "Lord of the Rings"
  And there is a library (has books) with the name "School library", book "Lord of the Rings"
```
with `book` being a transient attribute, and there being a model named `Book`.

What happens in this case is: `cucumber_factory` will decide that `book` is an association, and then search all previously created objects for an object where any attribute matches "Lord of the Rings".

I'm not sure what a good solution would be. We could possibly validate that the object returned is of the expected type?

**Comment by makmic** [comment]
After looking at the described case more closely, we found out that it seems to affect only named records (`book "LotR"`) but not references to the last record (`book above`). Furthermore, it seems that the problem could also affect non-transient associations. Lets have a look at this example:

```cucumber
1 Given "LotR" is a book 
2   And there is a library with the book "LotR"
3   And there is a library with the book "LotR"
``` 
* In line 1 CucumberFactory (CF) remembers that there is a `Book` instance with the name "LotR" (see `remember_record_names`)
* In line 2 CF creates a library with the correct book **and seems to remembers that library under the name "LotR".**
* In line 3 CF finds a record called "LotR", but its a library. CF creates a new library that is associated with the library before.

If my assumption is correct, this would be a problem independent whether its a transient association or not. The problem seems to be that a record is remembered under all its string and integer attribute values. We could either solve this by excluding association names from `remember_record_names` or by tuning the association lookup that it respects the given class. The latter could be tricky, as we have to be able to associate the record for all (non-abstract) superclasses later on.

**Comment by makmic** [comment]
I could not confirm the behavior dreaded above. The following spec just works fine:
```ruby
it 'does not overwrite references when associating new records with an existing reference' do
  invoke_cucumber_step('"reviewer" is a user with the id "1"')
  movie1 = invoke_cucumber_step('there is a movie with the reviewer "reviewer" and the id "2"')
  movie2 = invoke_cucumber_step('there is a movie with the reviewer "reviewer" and the id "3"')

  expect(movie1.reviewer_id).to eq(1)
  expect(movie2.reviewer_id).to eq(1)
end
```

The (string or int) attributes stored by `remember_record_names` are always parsed by `attribute_value`, which resolves associations prior to passing it further on.

**Comment by FLeinzi** [comment]
There will still be an issue with an factory like this, where `book` is an and transient attribute and there is no association named `book` on `Library`
```
factory :library do
  transient do
    book { 'Some title' }
  end

  new_book_ids do
    book ? [Book.find_by_title(book).id] : []
  end
end
```
with steps like this
```
Given there is a library with the book "Lord of the Rings"
  And there is a library with the book "Lord of the Rings"
```
Since you have not created the book "Lord of the Rings" record in a previous step, cucumber_factory will not find it under its name and will reference the first library instead.

We will not fix this scenario in cucumber_factory and you will have to fix it in your project, e.g. by renaming the transient attribute to `book_title` (no class constant).

**Comment by makmic** [comment]
Thanks for providing the (apparently) single broken example! I wanted to point out that normally this wouldn't be an issue if "library" and "book" would be associated normally. In that case, cucumber_factory would _not_ link the library with the name "Lord of the Ring".
